### ISSUE TITLE
Spyder is not launching from anaconda navigator, which i just have installed.

### ISSUE THREAD

**Issue by Charchil2020** [Charchil2020/Anaconda-spyder#1]
While launching spyder from anaconda navigator or directly from the menu, it is showing the given message:
Traceback (most recent call last):
File "C:\Users\charchil\anaconda3\Scripts\spyder-script.py", line 6, in 
from spyder.app.start import main
File "C:\Users\charchil\anaconda3\lib\site-packages\spyder\app\start.py", line 22, in 
import zmq
File "C:\Users\charchil\AppData\Roaming\Python\Python37\site-packages\zmq\__init__.py", line 47, in 
from zmq import backend
File "C:\Users\charchil\AppData\Roaming\Python\Python37\site-packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\charchil\AppData\Roaming\Python\Python37\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\charchil\AppData\Roaming\Python\Python37\site-packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\charchil\AppData\Roaming\Python\Python37\site-packages\zmq\backend\select.py", line 28, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\charchil\AppData\Roaming\Python\Python37\site-packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from 'zmq.backend.cython' (C:\Users\charchil\AppData\Roaming\Python\Python37\site-packages\zmq\backend\cython\__init__.py)

**Comment by Charchil2020** [comment]
@ccordoba12 please help!!

**Comment by ccordoba12** [comment]
Please remove this directory

> C:\Users\charchil\AppData\Roaming\Python\Python37

to get Spyder back to life. For next time, please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs), that explains how to solve problems that arise by mixing pip and conda packages (which is your case).

**Comment by Charchil2020** [comment]
> Please remove this directory
> 
> > C:\Users\charchil\AppData\Roaming\Python\Python37
> 
> to get Spyder back to life. For next time, please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs), that explains how to solve problems that arise by mixing pip and conda packages (which is your case).

Thank you so much for your help and instant reply :).
